output: "{{.Dir}}/README.md"
header: |-
  [![Go Report Card](https://goreportcard.com/badge/github.com/fritzkeyzer/conf)](https://goreportcard.com/report/github.com/fritzkeyzer/conf)
  [![GitHub Actions](https://github.com/fritzkeyzer/conf/workflows/Test/badge.svg)](https://github.com/fritzkeyzer/conf/actions?query=workflow%3ATest+branch%3Amaster)
  [![Go Reference](https://pkg.go.dev/badge/github.com/fritzkeyzer/conf.svg)](https://pkg.go.dev/github.com/fritzkeyzer/conf)
repository:
  url: https://github.com/fritzkeyzer/conf
  defaultBranch: master
  path: /
